[code]
editor = 'nvim'
lang = 'cpp'
editor_envs = ['XDG_CONFIG_HOME=~/.leetcode']

[cookies]
csrf = '<your-leetcode-csrf-token>'
session = '<your-leetcode-session-key>'
site = 'leetcode.com'

[storage]
cache = 'Problems'
code = 'code'
root = '~/.leetcode'
scripts = 'scripts'
